# Generated by Django 5.1.5 on 2025-03-16 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
